# Generated by Django 5.1.1 on 2024-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_rename_job_image_jobmodel_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='category',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('project_based', 'Project Based')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
