# Generated by Django 5.1.1 on 2024-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
