# Generated by Django 5.1.1 on 2024-10-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
